# Generated by Django 4.1.2 on 2023-02-18 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homep', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
            ],
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
