# Generated by Django 4.1.2 on 2023-02-18 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homep', '0002_tutorial_delete_member'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tutorial',
            new_name='Contactdb',
        ),
    ]
